version: "3.8"

services:
  # Front - prod (build)
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "8000:8443"
    networks:
      - front
    restart: on-failure
    profiles:
      - prod
    volumes:
      - shared_ssl:/etc/ssl
    env_file:
      - .env

  # Front - dev (live server)
  front_dev:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: front_dev
    volumes:
      - shared_ssl:/etc/ssl
      - /app/node_modules
      - type: bind
        source: ./front/app
        target: /app
    ports:
      - "8000:8000"
    networks:
      - front
    restart: on-failure
    profiles:
      - dev

  # Back - authentification
  authentification:
    build:
      context: ./authentification
      dockerfile: Dockerfile
    container_name: authentification
    ports:
      - "8001:8001"
    volumes:
      - ./authentification:/app
      - shared_media:/app/media
      - shared_ssl:/etc/ssl
    networks:
      - back
    depends_on:
      - data_base
    env_file:
      - .env
    restart: on-failure

  profile:
    build:
      context: ./profile
      dockerfile: Dockerfile
    container_name: profile
    volumes:
      - shared_media:/app/media
      - shared_ssl:/etc/ssl
      - ./profile/profileApp:/profileApp
    # ports:
    # - "8002:8002"
    networks:
      - back
    depends_on:
      - data_base
    env_file:
      - .env
    restart: on-failure

  # Back - data base
  data_base:
    build:
      context: ./data_base
      dockerfile: Dockerfile
    container_name: data_base
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data_base_data:/var/lib/postgresql/data
      - shared_ssl:/etc/ssl
    restart: always
    networks:
      - back

  # Back - friendship
  friendship:
    build:
      context: ./friendship
      dockerfile: Dockerfile
    container_name: friendship
    ports:
      - "8003:8003"
    volumes:
      - ./friendship/friendshipApp:/friendshipApp
      - shared_ssl:/etc/ssl
    networks:
      - back
    depends_on:
      - data_base
    env_file:
      - .env
    restart: on-failure

  # Back - game
  game:
    build:
      context: ./game
      dockerfile: Dockerfile
    container_name: game
    ports:
      - "8009:8009"
    volumes:
      - ./game/app:/app
      - shared_ssl:/etc/ssl
    networks:
      - back
    depends_on:
      - data_base
    env_file:
      - .env
    restart: on-failure

volumes:
  data_base_data:
  shared_media:
  shared_ssl:

networks:
  front:
    driver: bridge
  back:
    driver: bridge
